id: P004315
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD105798
  title: རོང་འབྲོག་མང་ཚོགས་ལ་ཉེ་བར་མཁོ་བའི་བཅའ་ཁྲིམས་ཤེས་བྱ།
  author: ''
  volumes:
    800a81b879dc4200beb0e69312463c21:
      image_group_id: I1PD105800
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
